"""init tables

Revision ID: 196947d4d1b3
Revises: 
Create Date: 2025-12-25 19:02:41.407297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import guard

# revision identifiers, used by Alembic.
revision: str = '196947d4d1b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='guard_acr').create(op.get_bind())
    op.create_table('guard_clients',
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('grant_types', sa.JSON(), nullable=False),
    sa.Column('response_types', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('authorization_code_lifetime_seconds', sa.Integer(), nullable=False),
    sa.Column('access_id_token_lifetime_seconds', sa.Integer(), nullable=False),
    sa.Column('refresh_token_lifetime_seconds', sa.Integer(), nullable=False),
    sa.Column('encrypt_jwk', sa.Text(), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_clients'))
    )
    op.create_index(op.f('ix_guard_clients_client_id'), 'guard_clients', ['client_id'], unique=False)
    op.create_index(op.f('ix_guard_clients_client_secret'), 'guard_clients', ['client_secret'], unique=False)
    op.create_index(op.f('ix_guard_clients_created_at'), 'guard_clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_clients_updated_at'), 'guard_clients', ['updated_at'], unique=False)
    op.create_table('guard_oauth_providers',
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', guard.models.base.EncryptedString(), nullable=False),
    sa.Column('client_secret', guard.models.base.EncryptedString(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_oauth_providers'))
    )
    op.create_index(op.f('ix_guard_oauth_providers_created_at'), 'guard_oauth_providers', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_oauth_providers_updated_at'), 'guard_oauth_providers', ['updated_at'], unique=False)
    op.create_table('guard_users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_users'))
    )
    op.create_index(op.f('ix_guard_users_created_at'), 'guard_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_users_email'), 'guard_users', ['email'], unique=False)
    op.create_index(op.f('ix_guard_users_email_verified'), 'guard_users', ['email_verified'], unique=False)
    op.create_index(op.f('ix_guard_users_phone'), 'guard_users', ['phone'], unique=False)
    op.create_index(op.f('ix_guard_users_phone_verified'), 'guard_users', ['phone_verified'], unique=False)
    op.create_index(op.f('ix_guard_users_updated_at'), 'guard_users', ['updated_at'], unique=False)
    op.create_table('guard_authorization_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('c_hash', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('authenticated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=True),
    sa.Column('acr', postgresql.ENUM('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='guard_acr', create_type=False), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=255), nullable=True),
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('client_id', guard.models.base.GUID(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['guard_clients.id'], name=op.f('fk_guard_authorization_codes_client_id_guard_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_authorization_codes_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_authorization_codes'))
    )
    op.create_index(op.f('ix_guard_authorization_codes_code'), 'guard_authorization_codes', ['code'], unique=True)
    op.create_index(op.f('ix_guard_authorization_codes_created_at'), 'guard_authorization_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_authorization_codes_expires_at'), 'guard_authorization_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guard_authorization_codes_updated_at'), 'guard_authorization_codes', ['updated_at'], unique=False)
    op.create_table('guard_grants',
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('client_id', guard.models.base.GUID(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['guard_clients.id'], name=op.f('fk_guard_grants_client_id_guard_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_grants_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_grants')),
    sa.UniqueConstraint('user_id', 'client_id', name=op.f('guard_grants_user_id_client_id_key'))
    )
    op.create_index(op.f('ix_guard_grants_created_at'), 'guard_grants', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_grants_updated_at'), 'guard_grants', ['updated_at'], unique=False)
    op.create_table('guard_login_sessions',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('response_type', sa.String(length=255), nullable=False),
    sa.Column('response_mode', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2048), nullable=True),
    sa.Column('nonce', sa.String(length=255), nullable=True),
    sa.Column('acr', postgresql.ENUM('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='guard_acr', create_type=False), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=255), nullable=True),
    sa.Column('client_id', guard.models.base.GUID(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['guard_clients.id'], name=op.f('fk_guard_login_sessions_client_id_guard_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_login_sessions'))
    )
    op.create_index(op.f('ix_guard_login_sessions_created_at'), 'guard_login_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_login_sessions_expires_at'), 'guard_login_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guard_login_sessions_token'), 'guard_login_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_guard_login_sessions_updated_at'), 'guard_login_sessions', ['updated_at'], unique=False)
    op.create_table('guard_oauth_accounts',
    sa.Column('account_id', sa.String(length=512), nullable=False),
    sa.Column('account_email', sa.String(length=512), nullable=True),
    sa.Column('access_token', guard.models.base.EncryptedString(), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('refresh_token', guard.models.base.EncryptedString(), nullable=True),
    sa.Column('oauth_provider_id', guard.models.base.GUID(), nullable=False),
    sa.Column('user_id', guard.models.base.GUID(), nullable=True),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oauth_provider_id'], ['guard_oauth_providers.id'], name=op.f('fk_guard_oauth_accounts_oauth_provider_id_guard_oauth_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_oauth_accounts_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_oauth_accounts')),
    sa.UniqueConstraint('oauth_provider_id', 'account_id', name=op.f('guard_oauth_accounts_oauth_provider_id_account_id_key')),
    sa.UniqueConstraint('oauth_provider_id', 'user_id', name=op.f('guard_oauth_accounts_oauth_provider_id_user_id_key'))
    )
    op.create_index(op.f('ix_guard_oauth_accounts_account_id'), 'guard_oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_guard_oauth_accounts_created_at'), 'guard_oauth_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_oauth_accounts_updated_at'), 'guard_oauth_accounts', ['updated_at'], unique=False)
    op.create_table('guard_refresh_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('authenticated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('client_id', guard.models.base.GUID(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['guard_clients.id'], name=op.f('fk_guard_refresh_tokens_client_id_guard_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_refresh_tokens_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_refresh_tokens'))
    )
    op.create_index(op.f('ix_guard_refresh_tokens_created_at'), 'guard_refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_refresh_tokens_expires_at'), 'guard_refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guard_refresh_tokens_token'), 'guard_refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_guard_refresh_tokens_updated_at'), 'guard_refresh_tokens', ['updated_at'], unique=False)
    op.create_table('guard_session_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_session_tokens_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_session_tokens'))
    )
    op.create_index(op.f('ix_guard_session_tokens_created_at'), 'guard_session_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_session_tokens_expires_at'), 'guard_session_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guard_session_tokens_token'), 'guard_session_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_guard_session_tokens_updated_at'), 'guard_session_tokens', ['updated_at'], unique=False)
    op.create_table('guard_oauth_sessions',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('oauth_provider_id', guard.models.base.GUID(), nullable=False),
    sa.Column('oauth_account_id', guard.models.base.GUID(), nullable=True),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oauth_account_id'], ['guard_oauth_accounts.id'], name=op.f('fk_guard_oauth_sessions_oauth_account_id_guard_oauth_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oauth_provider_id'], ['guard_oauth_providers.id'], name=op.f('fk_guard_oauth_sessions_oauth_provider_id_guard_oauth_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_oauth_sessions'))
    )
    op.create_index(op.f('ix_guard_oauth_sessions_created_at'), 'guard_oauth_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_oauth_sessions_expires_at'), 'guard_oauth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guard_oauth_sessions_token'), 'guard_oauth_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_guard_oauth_sessions_updated_at'), 'guard_oauth_sessions', ['updated_at'], unique=False)
    op.create_table('guard_registration_sessions',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('flow', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('oauth_account_id', guard.models.base.GUID(), nullable=True),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oauth_account_id'], ['guard_oauth_accounts.id'], name=op.f('fk_guard_registration_sessions_oauth_account_id_guard_oauth_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_registration_sessions'))
    )
    op.create_index(op.f('ix_guard_registration_sessions_created_at'), 'guard_registration_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_registration_sessions_expires_at'), 'guard_registration_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guard_registration_sessions_token'), 'guard_registration_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_guard_registration_sessions_updated_at'), 'guard_registration_sessions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guard_registration_sessions_updated_at'), table_name='guard_registration_sessions')
    op.drop_index(op.f('ix_guard_registration_sessions_token'), table_name='guard_registration_sessions')
    op.drop_index(op.f('ix_guard_registration_sessions_expires_at'), table_name='guard_registration_sessions')
    op.drop_index(op.f('ix_guard_registration_sessions_created_at'), table_name='guard_registration_sessions')
    op.drop_table('guard_registration_sessions')
    op.drop_index(op.f('ix_guard_oauth_sessions_updated_at'), table_name='guard_oauth_sessions')
    op.drop_index(op.f('ix_guard_oauth_sessions_token'), table_name='guard_oauth_sessions')
    op.drop_index(op.f('ix_guard_oauth_sessions_expires_at'), table_name='guard_oauth_sessions')
    op.drop_index(op.f('ix_guard_oauth_sessions_created_at'), table_name='guard_oauth_sessions')
    op.drop_table('guard_oauth_sessions')
    op.drop_index(op.f('ix_guard_session_tokens_updated_at'), table_name='guard_session_tokens')
    op.drop_index(op.f('ix_guard_session_tokens_token'), table_name='guard_session_tokens')
    op.drop_index(op.f('ix_guard_session_tokens_expires_at'), table_name='guard_session_tokens')
    op.drop_index(op.f('ix_guard_session_tokens_created_at'), table_name='guard_session_tokens')
    op.drop_table('guard_session_tokens')
    op.drop_index(op.f('ix_guard_refresh_tokens_updated_at'), table_name='guard_refresh_tokens')
    op.drop_index(op.f('ix_guard_refresh_tokens_token'), table_name='guard_refresh_tokens')
    op.drop_index(op.f('ix_guard_refresh_tokens_expires_at'), table_name='guard_refresh_tokens')
    op.drop_index(op.f('ix_guard_refresh_tokens_created_at'), table_name='guard_refresh_tokens')
    op.drop_table('guard_refresh_tokens')
    op.drop_index(op.f('ix_guard_oauth_accounts_updated_at'), table_name='guard_oauth_accounts')
    op.drop_index(op.f('ix_guard_oauth_accounts_created_at'), table_name='guard_oauth_accounts')
    op.drop_index(op.f('ix_guard_oauth_accounts_account_id'), table_name='guard_oauth_accounts')
    op.drop_table('guard_oauth_accounts')
    op.drop_index(op.f('ix_guard_login_sessions_updated_at'), table_name='guard_login_sessions')
    op.drop_index(op.f('ix_guard_login_sessions_token'), table_name='guard_login_sessions')
    op.drop_index(op.f('ix_guard_login_sessions_expires_at'), table_name='guard_login_sessions')
    op.drop_index(op.f('ix_guard_login_sessions_created_at'), table_name='guard_login_sessions')
    op.drop_table('guard_login_sessions')
    op.drop_index(op.f('ix_guard_grants_updated_at'), table_name='guard_grants')
    op.drop_index(op.f('ix_guard_grants_created_at'), table_name='guard_grants')
    op.drop_table('guard_grants')
    op.drop_index(op.f('ix_guard_authorization_codes_updated_at'), table_name='guard_authorization_codes')
    op.drop_index(op.f('ix_guard_authorization_codes_expires_at'), table_name='guard_authorization_codes')
    op.drop_index(op.f('ix_guard_authorization_codes_created_at'), table_name='guard_authorization_codes')
    op.drop_index(op.f('ix_guard_authorization_codes_code'), table_name='guard_authorization_codes')
    op.drop_table('guard_authorization_codes')
    op.drop_index(op.f('ix_guard_users_updated_at'), table_name='guard_users')
    op.drop_index(op.f('ix_guard_users_phone_verified'), table_name='guard_users')
    op.drop_index(op.f('ix_guard_users_phone'), table_name='guard_users')
    op.drop_index(op.f('ix_guard_users_email_verified'), table_name='guard_users')
    op.drop_index(op.f('ix_guard_users_email'), table_name='guard_users')
    op.drop_index(op.f('ix_guard_users_created_at'), table_name='guard_users')
    op.drop_table('guard_users')
    op.drop_index(op.f('ix_guard_oauth_providers_updated_at'), table_name='guard_oauth_providers')
    op.drop_index(op.f('ix_guard_oauth_providers_created_at'), table_name='guard_oauth_providers')
    op.drop_table('guard_oauth_providers')
    op.drop_index(op.f('ix_guard_clients_updated_at'), table_name='guard_clients')
    op.drop_index(op.f('ix_guard_clients_created_at'), table_name='guard_clients')
    op.drop_index(op.f('ix_guard_clients_client_secret'), table_name='guard_clients')
    op.drop_index(op.f('ix_guard_clients_client_id'), table_name='guard_clients')
    op.drop_table('guard_clients')
    sa.Enum('LEVEL_0', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='guard_acr').drop(op.get_bind())
    # ### end Alembic commands ###
