"""add role、permission table

Revision ID: 30f91bac0eda
Revises: 3a2348b913b5
Create Date: 2025-12-30 18:12:10.358547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import guard


# revision identifiers, used by Alembic.
revision: str = '30f91bac0eda'
down_revision: Union[str, Sequence[str], None] = '3a2348b913b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_permissions')),
    sa.UniqueConstraint('code', name=op.f('guard_permissions_code_key'))
    )
    op.create_index(op.f('ix_guard_permissions_created_at'), 'guard_permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_permissions_updated_at'), 'guard_permissions', ['updated_at'], unique=False)
    op.create_table('guard_roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('id', guard.models.base.GUID(), nullable=False),
    sa.Column('created_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', guard.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_roles')),
    sa.UniqueConstraint('name', name=op.f('guard_roles_name_key'))
    )
    op.create_index(op.f('ix_guard_roles_created_at'), 'guard_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_guard_roles_updated_at'), 'guard_roles', ['updated_at'], unique=False)
    op.create_table('guard_roles_permissions',
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('permission_id', guard.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['guard_permissions.id'], name=op.f('fk_guard_roles_permissions_permission_id_guard_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_roles_permissions_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_guard_roles_permissions'))
    )
    op.create_table('guard_users_permissions',
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('permission_id', guard.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['guard_permissions.id'], name=op.f('fk_guard_users_permissions_permission_id_guard_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_users_permissions_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_guard_users_permissions'))
    )
    op.create_table('guard_users_roles',
    sa.Column('user_id', guard.models.base.GUID(), nullable=False),
    sa.Column('role_id', guard.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['guard_roles.id'], name=op.f('fk_guard_users_roles_role_id_guard_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['guard_users.id'], name=op.f('fk_guard_users_roles_user_id_guard_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_guard_users_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guard_users_roles')
    op.drop_table('guard_users_permissions')
    op.drop_table('guard_roles_permissions')
    op.drop_index(op.f('ix_guard_roles_updated_at'), table_name='guard_roles')
    op.drop_index(op.f('ix_guard_roles_created_at'), table_name='guard_roles')
    op.drop_table('guard_roles')
    op.drop_index(op.f('ix_guard_permissions_updated_at'), table_name='guard_permissions')
    op.drop_index(op.f('ix_guard_permissions_created_at'), table_name='guard_permissions')
    op.drop_table('guard_permissions')
    # ### end Alembic commands ###
